"""empty message

Revision ID: 0bba726a2036
Revises: abeddb038354
Create Date: 2022-07-29 21:53:17.054276

"""

# revision identifiers, used by Alembic.
revision = '0bba726a2036'
down_revision = 'abeddb038354'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
