"""List

Revision ID: 1f4db4941869
Revises: 543414f8a84f
Create Date: 2022-07-28 21:34:23.251107

"""

# revision identifiers, used by Alembic.
revision = '1f4db4941869'
down_revision = '543414f8a84f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ADDED', 'ACTIVE', 'INACTIVE', 'REMOVED', name='statustype'), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enquiries_timestamp'), 'enquiries', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enquiries_timestamp'), table_name='enquiries')
    op.drop_table('enquiries')
    # ### end Alembic commands ###

